kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/arunhari82/dotnet-eShopOnWeb.git'
    openshift.io/generated-by: OpenShiftWebConsole
  name: web-app
  labels:
    app: web-app
    app.kubernetes.io/component: web-app
    app.kubernetes.io/instance: web-app
    app.kubernetes.io/name: web-app
    app.kubernetes.io/part-of: dotnet-s2i-demo
    app.openshift.io/runtime: dotnet
    app.openshift.io/runtime-version: 7.0-ubi8
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'web-app:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'dotnet:7.0-ubi8'
      env:
        - name: DOTNET_STARTUP_PROJECT
          value: src/Web/Web.csproj
        - name: ASPNETCORE_URLS
          value: 'http://+:5106'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/arunhari82/dotnet-eShopOnWeb.git'
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: web-app-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: web-app-github-webhook-secret
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial
