kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/arunhari82/dotnet-eShopOnWeb.git'
    deployment.kubernetes.io/revision: '5'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"web-app:latest","namespace":"dotnet"},"fieldPath":"spec.template.spec.containers[?(@.name==\"web-app\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  resourceVersion: '225433'
  name: web-app
  uid: faa3b782-df2d-405a-a58f-67b8485d7c0b
  creationTimestamp: '2023-04-27T14:24:59Z'
  generation: 7
  labels:
    app: web-app
    app.kubernetes.io/component: web-app
    app.kubernetes.io/instance: web-app
    app.kubernetes.io/name: web-app
    app.kubernetes.io/part-of: eShopOnWeb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
        deployment: web-app
    spec:
      containers:
        - name: web-app
          image: >-
            image-registry.openshift-image-registry.svc:5000/dotnet/web-app@sha256:d6026bbde17e6890adc6fad38f666a05c61fab7018abc49c8bce313f90e78920
          env:
            - name: ASPNETCORE_URLS
              value: 'http://+:8080'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: webapp-sa
      serviceAccount: webapp-sa
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
